#' Power plant average hourly output data
#'
#' "This dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the power plant was set to work with full load. Features consist of hourly average ambient variables Temperature (T), Ambient Pressure (AP), Relative Humidity (RH) and Exhaust Vacuum (V) to predict the net hourly electrical energy output (PE)  of the plant. A combined cycle power plant (CCPP) is composed of gas turbines (GT), steam turbines (ST) and heat recovery steam generators. In a CCPP, the electricity is generated by gas and steam turbines, which are combined in one cycle, and is transferred from one turbine to another. While the Vacuum is collected from and has an effect on the Steam Turbine, the other three of the ambient variables effect the GT performance."
#' From Tufekci, P. (2014) "Prediction of full load electrical power output of a base load operated combined cycle power plant using machine learning methods". _Electrical Power and Energy Systems_, 60, 126-140.
#' Features consist of hourly average ambient variables
#' Temperature (T) in the range 1.81°C and 37.11°C,
#' Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
#' Relative Humidity (RH) in the range 25.56% to 100.16%
#' Exhaust Vacuum (V) in the range 25.36-81.56 cm Hg
#' Net hourly electrical energy output (EP) 420.26-495.76 MW
#' The averages are taken from various sensors located around the plant that record the ambient variables every second. The variables are given without normalization.

#'
#' @format a \code{data.frame} with 9568 observations on 5 variables:
#' \describe{
#'   \item{AT}{Ambient temperature in degrees C}
#'   \item{V}{Exhaust vacuum cm Hg}
#'   \item{AP}{Ambient pressure milibar}
#'   \item{RH}{Relative humidity percent}
#'   \item{PE}{Net hourly electrical energy output MW}
#' }
#'
#' @name powerplantoutput
#' @docType data
#' @references Tufekci, P. (2014) "Prediction of full load electrical power output of a base load operated combined cycle power plant using machine learning methods". _Electrical Power and Energy Systems_, 60, 126-140.
#' @source https://www.kaggle.com/datasets/gova26/airpressure
#' @keywords data powerplant energy temperature
#' @examples
#' set.seed(406)
#' library(dplyr)
#' powerplantoutput <- powerplantoutput %>% mutate(ids = 1:dim(powerplantoutput)[1])
#' floor(0.7*length(powerplantoutput$ids)) # Want 70% of the data for training
#' training_data <- slice_sample(powerplantoutput, prop = 0.7)
#' dim(training_data)
#' test_data <- anti_join(powerplantoutput, training_data) #all unused observations in training are for test
#' m1 <- lm(PE ~ AT + V + AP + RH, data = training_data)
#' summary(m1)
#' library(car)
#' vif(m1)
#' m2 <- lm(PE ~ AT*RH + V + AP, data = training_data)
#' library(effects)
#' plot(allEffects(m2), 1, grid = TRUE, multiline = TRUE, ci.style = "bands")
#' plot(allEffects(m2), 2, grid = TRUE, multiline = TRUE, ci.style = "bands")
#' plot(allEffects(m2), 3, grid = TRUE, multiline = TRUE, ci.style = "bands")
#'
#' # Based on http://thomasleeper.com/Rcourse/Tutorials/olsinteractionplots2.html
#' nAT <- seq(from=min(training_data$AT),to=max(training_data$AT),length.out=20)
#' nRH <- seq(from=min(training_data$RH),to=max(training_data$RH),length.out=20)
#' z <- outer(nAT, nRH, FUN = function(a, b) predict(m2, data.frame(AT = a, RH = b,V=rep(mean(training_data$V),20),AP=rep(mean(training_data$AP),20)))) #Creates surface of predicted mean responses across predictor values
#' persp(nAT, nRH, z, theta = 45, phi = 10, shade = 0.75, xlab = "AT", ylab = "RH",   zlab = "PE")
#' par(mai = rep(0.2, 4))
#' layout(matrix(1:4, nrow = 2, byrow = TRUE))
#' s <- sapply(c(45, 135, 225, 315), function(i) persp(nAT, nRH, z, theta = i, phi = 10,
#'  shade = 0.75, xlab = "AT", ylab = "RH", zlab = "PE"))
"powerplantoutput"
